apiVersion: v1
kind: Service
metadata:
  name: health-integration-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: health-integration-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
